### ISSUE TITLE
Remove inter-extras dependencies

### ISSUE THREAD

**Issue by johann-petrak** [GateNLP/python-gatenlp#167]
Make sure we do not unintentionally depend on an extra which might not be installed. 

There are several possible ways how this could happen:

* as it happened with the client module: we import classes in `__init__.py` for convenience, but this makes us depend on the union of packages required by all those classes. Instead: only allow to import those classes directly from their own modules
* as it happened with document visualization: the code tries to detect if we run in notebook or not but for this the ipython-related modules are required which are not a requirement for basic gatenlp. Instead: move the imports to where required and/or enclose in try/catch

**Comment by johann-petrak** [comment]
Fixed for the client modules

**Comment by johann-petrak** [comment]
Visualization: this happens because of the way how we currently map document formats to the classes that handle the format in the serialization/default module: currently we import all classes and then map the methods for saving/loading. Importing all classes requires all the packages each of the classes requires.

Possible ways to fix this:
* delay importing the extra-specific packages to class initialization (or possibly other module methods): this should be easy and provide a quick fix
* instead of mapping to an imported class method, map to a function/lambda that determines the class method only when needed in a lazy way

For now, the first solution looks like the better option.

**Comment by johann-petrak** [comment]
If running under starboard (starboard.gg) and displaying a doc:

```
Traceback (most recent call last):
  File "/lib/python3.9/site-packages/gatenlp/[document.py](http://document.py/)", line 877, in _repr_html_
    if in_colab():
  File "/lib/python3.9/site-packages/gatenlp/[utils.py](http://utils.py/)", line 298, in in_colab
    from IPython.core import getipython
ModuleNotFoundError: No module named 'IPython'
```
