### ISSUE TITLE
Starting the GATE slave error: dumps empty lines

### ISSUE THREAD

**Issue by johann-petrak** [GateNLP/python-gatenlp#35]
There are situations where failure of starting the gate slave loops through producing empty lines on the console output. 

One such situation seems to be: `GATE_HOME` points to a Gate 8.6.1 distribution. 

This produces exception:
```
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: gate/creole/Plugin
at java.lang.Class.getDeclaredMethods0(Native Method)
at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
at java.lang.Class.getMethod0(Class.java:3018)
at java.lang.Class.getMethod(Class.java:1784)
at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: gate.creole.Plugin
at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
... 7 more
```

And the following on the python side after terminating with Ctrl-C:
```
KeyboardInterrupt                         Traceback (most recent call last)
<ipython-input-2-7c5ca78aad61> in <module>
----> 1 gs = GateSlave(port=33333,start=True)

~/software/anaconda3/envs/polads/lib/python3.6/site-packages/gatenlp/gateslave.py in __init__(self, port, start, java, host, gatehome, platform, auth_token, use_auth_token, log_actions, keep)
    280                 if line == "PythonSlaveRunner.java: server start NOT OK":
    281                     raise Exception("Could not start server, giving up")
--> 282                 print(line, file=sys.stderr)
    283             atexit.register(self.close)
    284         self.gateway = JavaGateway(
```

**Comment by johann-petrak** [comment]
This should be fixed now, new gatenlp  version 0.9.5
